### ISSUE TITLE
Best Practice - how to replace a mapped endpoint response?

### ISSUE THREAD

**Issue by szymon-kazmierczak** [andrzejchm/RESTMock#86] opened 2018-08-09 16:04 UTC
I was wondering if you have the best practice for replacing an already mapped endpoint.

I have endpoints mapped as such (just an example):
```
val getSettings: MatchableCall
        get() = whenRequested(allOf(
                isGET(),
                pathStartsWith("/api/v2/"),
                pathEndsWithIgnoringQueryParams("settings.json")
        ))
```

I then have an initDefaultMocks function that maps endpoints with default responses. See below:
```
fun initDefaultMocks() {
        postOauthMobile.thenReturnEmpty(200)
        getSettings.thenReturnEmpty(200)
        getUser.thenReturnEmpty(200)
        }
```
What that means is that sometimes I need to remove the mock and add a different one (unique cases with their own mocks). 
What is the best way to replace that endpoint mock? Ideally I'd like to be able to provide an endpoint matcher and remove/replace the response for that 🤔

**Comment by szymon-kazmierczak** [comment] 2018-08-10 08:29
I tried the following: 

```
fun updateEndpointResponse(oldMock: MatchableCall, newMockedResponse: String) {
        RESTMockServer.replaceMatchableCall(oldMock, oldMock.thenReturnString(newMockedResponse))
    }
```
But I get the "There are more than one response matching this request:". Something I guess could work if requestMatcher was public and not package level.
```
fun updateEndpointResponse(oldMock: MatchableCall, newMockedResponse: String) {
        RESTMockServer.replaceMatchableCall(oldMock, oldMock.requestMatcher.thenReturnString(newMockedResponse))
    }
```

**Comment by andrzejchm** [comment] 2018-10-10 10:19
keep in mind that all methods, like `thenReturn*` return the MatchableCall that you should store somewhere in order to be able to replace them with `RESTMockServer.replaceMatchableCall`. something like:
```kotlin
MatchableCall oauthMobileCall;
MatchableCall settingsCall;
MatchableCall userCall;
fun initDefaultMocks() {
       oauthMobileCall = postOauthMobile.thenReturnEmpty(200)
        settingsCall = getSettings.thenReturnEmpty(200)
        userCall = getUser.thenReturnEmpty(200)
        }
...

fun someFunction() {
    RESTMockServer.replaceMatchableCall(oauthMobileCall, postOauthMobile.thenReturnString(newOauthResponse))

    RESTMockServer.replaceMatchableCall(settingsCall, postOauthMobile.thenReturnString(newSettingsResponse))

    RESTMockServer.replaceMatchableCall(settingsCall, postOauthMobile.thenReturnString(newUserResponse))
}
```

I agree this could be improved and will take a look into it in one of the future releasess

**Comment by andrzejchm** [comment] 2019-07-23 18:44
closing the issue for now as the problem is solved. I'm working on a new version of RESTMock, hopefully in Kotlin, which will have a little bit clearer APIs

**Closed by andrzejchm** 2019-07-23 18:44 UTC
Labels: enhancement
